# Generated by Django 4.1.7 on 2023-02-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genereName', models.CharField(help_text='Introduce el genero de la pelicula', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summaryResume', models.TextField(help_text='Introduce un resumen de la pelicula', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='movieTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(help_text='Introduce el titulo de la pelicula', max_length=64)),
                ('genere', models.ManyToManyField(to='managers.genere')),
                ('nameManager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.namemanager')),
                ('summary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.summary')),
            ],
        ),
    ]
